#undef _vector_zero_f
#undef _vector_minus_f
#undef _vector_i_plus_f
#undef _vector_i_minus_f
#undef _vector_mul_f
#undef _vector_mulc_f
#undef _vector_mulc_star_f
#undef _vector_add_f
#undef _vector_sub_f
#undef _vector_i_add_f
#undef _vector_i_sub_f
#undef _vector_add_assign_f
#undef _vector_sub_assign_f
#undef _vector_i_add_assign_f
#undef _vector_i_sub_assign_f
#undef _vector_prod_f
#undef _vector_prod_re_f
#undef _vector_prod_im_f
#undef _vector_mulc_add_assign_f
#undef _vector_mul_add_assign_f
#undef _vector_lc_f
#undef _vector_lc_add_assign_f
#undef _vector_clc_f
#undef _vector_clc_add_assign_f
#undef _vector_prod_assign_f
#undef _vector_prod_add_assign_re_f
#undef _vector_prod_add_assign_im_f
#undef _vector_prod_sub_assign_re_f
#undef _vector_prod_sub_assign_im_f
#undef _vector_project_f
#undef _algebra_vector_mul_add_assign_gpu_f_flt
#undef _algebra_vector_mul_add_assign_gpu_f
